### ISSUE TITLE
HAZ changed the website design

### ISSUE THREAD

**Issue by x5ejf9f** [mx4k/RNDplus4free#2]
Hello,

the script is not working anymore because HAZ changed the website design.
The Articletext is still in the html source code.

Best regards

**Comment by mx4k** [comment]
I can confirm, the site script isn't working anymore.
Where did you find the article text in the sourcecode? If it's still there, I'll fix it.

**Comment by x5ejf9f** [comment]
It starts in Row 28/29 with the operator description. Thats the part which is hidden from the Payment Wall.
The articletext starts with articlebody. 

Thanks in advance

**Comment by mx4k** [comment]
Script reworked to work again. HAZ.de and NeuePresse.de are working again. The other pages aren't working anymore (until they are using the new design too).
