### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by x5ejf9f** [mx4k/RNDplus4free#5]
Hey,

I got a weird bug on my computer, laptop and a other computer in a different network. 

Using Firefox with UBlock.

Sometimes the HAZ+ articles are readable but there is the text first in orange and after the orange text it shows the article text a second time in white. 
Thats the first bug which is not so bad because you can still read the article text.

The second one shows me the article text for 1 second after refreshing but then its away and I just see the paywall. 

I dont know why. tbh.

Can make a Video if you like.

thanks in advance

**Comment by mx4k** [comment]
Do you mean "uBlock Origin" or "uBlock"? If it#s the second, I would really recommend to switch.
Did you try without other addons jsut with tampermonkey?

**Comment by x5ejf9f** [comment]
Old cookies was the problem.
