### ISSUE TITLE
Skript funktioniert nicht richtig

### ISSUE THREAD

**Issue by flooorian1** [mx4k/RNDplus4free#7]
Der Text lädt kurz und bleibt ca, 1s stehen, wird dann aber wieder entfernt und es kommt ein Banner, dass man doch ein Abo kaufen soll bzw. der Blurr-Effekt bleibt dauerhaft.

z.B. hier probiert:
https://www.sn-online.de/lokales/hannover/landgericht-hannover-so-haben-sich-morde-in-nordstadt-und-mitte-abgespielt-K4YLW6W7MRE7JMFCOJTLKJNLWE.html
aber auch bei ndz.de und haz.de bei mehreren Beiträgen getestet

![2024-06-03_133858_Laptop_ShareX](https://github.com/mx4k/RNDplus4free/assets/99684355/f7f632be-b387-4f04-bca9-04d238c46cba)

**Comment by mx4k** [comment]
Schau mal bitte nach, ob du wirklich die aktuellste Version (v0.5.10a) installiert hast.

**Comment by mx4k** [comment]
Kann ich leider nicht nachstellen. Versuche bitte den Cache zu leeren oder einen anderen Browser (Firefox funktioniert bei mir) einzusetzen.
